- hosts: all
    
  roles:
    - role: geerlingguy.pip
      become: yes
      tags: install
      
  tasks:
    - name: Add packeges
      apt:
        name:
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes
      become: true  
      tags: install
      
    - name: Prepare .env file
      ansible.builtin.template:
        src: templates/.env.j2
        dest: "{{ env_path }}"
        mode: '660'
      tags: install
      
    - name: Start Redmine_
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        restart_policy: always
        ports:
          - 80:3000
        env_file: "{{ env_path }}"
      tags: deploy



- name: Install and setup Datadog Agent
  hosts: webservers
  tags: install-datadog
         
  roles:
    - role: datadog.datadog
      vars_files:
         - group_vars/webservers/vars.yml
      
      become: yes

           
  
  
            
         
      
