- hosts: all
  #vars_files:
        #- group_vars/webservers/vars.yml #for hexlet-chek passing
        
  roles:
    - role: geerlingguy.pip
      become: yes
      tags: install

    - role: geerlingguy.docker
      vars_files:
        - group_vars/webservers/vars.yml #for hexlet-chek passing
      become: yes
      tags: install-docker
  
  tasks:
    - name: Prepare .env file
      ansible.builtin.template:
        src: templates/.env.j2
        dest: "{{ env_path }}"
        mode: '660'
      tags: install
      
      
      
    - name: Start Redmine_
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        restart_policy: always
        ports:
          - 80:3000
        env_file: "{{ env_path }}"
      tags: deploy



- name: Install and setup Datadog Agent
  hosts: webservers
  tags: install-datadog
         
  roles:
    - role: datadog.datadog
      become: yes

           
  
  
            
         
      
