- hosts: all
  remote_user: '{{ansible_user}}'

  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
            state: present
      #become: true
      #remote_user: alex999
      tags: install

  tasks:
    - name: Install pip
      ansible.builtin.import_role:
        name: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
      #become: true
      #remote_user: alex999
      tags: install

    - name: Prepare .env file
      ansible.builtin.template:
        src: templates/.env
        dest: ~/.env
        mode: '660'
      #become: true
      #remote_user: alex999
      tags: deploy

    - name: Install Redmine
      community.docker.docker_container:
        name: redmine
        image: redmine:latest
        pull: true
        restart: true
        state: started
        ports:
          - "3000:3000"
        env_file: ~/.env
        #env:
          #REDMINE_DB_POSTGRES: "{{ db_host }}"
          #REDMINE_DB_PORT: "{{ db_port }}"
          #REDMINE_DB_DATABASE: "{{ db_name }}"
          #REDMINE_DB_USERNAME: "{{ db_user }}"
          #REDMINE_DB_PASSWORD: "{{ db_user_password }}"
      #become: true
      #remote_user: alex999
      tags: deploy

- hosts: webservers

  tasks:
   - name: Install datadog
     import_role:
        name: datadog.datadog
     become: true
     tags: install-datadog

  vars:
    datadog_api_key: '{{ datadog_api_keys }}'
    datadog_site: datadoghq.eu
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: Check website health
            url: 'https://hexlet.web-programmer.kz'

