---
db_host: "rc1d-cfepupk6s6a8y96q.mdb.yandexcloud.net" 
db_port: "6432"
db_name: "db1"
db_user: "user1"

env_path: ~/.env
container_name: redmine
docker_image: redmine:latest   
pip_install_packages_name: docker

#geerlingguy.pip
pip_install_packages:
    - name: docker
    - name: awscli

# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_packages:
    - "docker-{{ docker_edition }}"
    - "docker-{{ docker_edition }}-cli"
    - "docker-{{ docker_edition }}-rootless-extras"
docker_packages_state: present

#Datadog 
datadog_site: datadoghq.eu
datadog_checks: 
    http_check:
        init_config:
        instances:
               - name: Redmine
                 url: http://0.0.0.0
                 timeout: 5
                 tags:
                   - app_redmine
                 collect_response_time: true
