---
#db_host: "rc1d-cfepupk6s6a8y96q.mdb.yandexcloud.net,rc1d-k5udleuo1w3go906.mdb.yandexcloud.net"
db_host: "rc1d-cfepupk6s6a8y96q.mdb.yandexcloud.net" 
db_port: "6432"
db_name: "db1"
db_user: "user1"
#db_password: "{{ db_user_password }}"
