---
db_host: "rc1d-cfepupk6s6a8y96q.mdb.yandexcloud.net" 
db_port: "6432"
db_name: "db1"
db_user: "user1"

env_dir: ~/.env
container_name: redmine
docker_image: redmine:latest
pip_install_packages_name: docker

