---
db_host: "rc1d-cfepupk6s6a8y96q.mdb.yandexcloud.net" 
db_port: "6432"
db_name: "db1"
db_user: "user1"

env_path: ~/.env
container_name: redmine
docker_image: redmine:latest   

#geerlingguy
docker_users: "{{ ansible_user }}"
pip_install_packages:
    - name: docker
    - name: awscli

docker_packages: 
    - "docker-ce"
    - "docker-ce-cli"
    - "docker-ce-rootless-extras"
docker_service_manage: true
docker_service_state: started #stopped  
docker_service_enabled: true
docker_restart_handler_state: restarted

#docker_install_compose_plugin: true
#docker_compose_package: docker-compose-plugin
#docker_compose_package_state: stoped
#docker_add_repo: true

#Datadog 
datadog_site: datadoghq.eu
datadog_checks: 
    http_check:
        init_config:
        instances:
               - name: Redmine
                 url: http://0.0.0.0
                 timeout: 5
                 tags:
                   - app_redmine
                 collect_response_time: true
